### ISSUE TITLE
Meta: issues with format repo

### ISSUE THREAD

**Issue by koczkatamas** [kaitai-io/kaitai_struct#97]
This meta task is for keeping track of the compiler issues of the format repo which makes the generated output noncompilable.

- [ ] [prohibit identifiers starting with digit](https://github.com/kaitai-io/kaitai_struct/issues/96)
- [ ] [io.size returns std::streampos in cpp-stl](https://github.com/kaitai-io/kaitai_struct/issues/95)
- [ ] [python invalid imports](https://github.com/kaitai-io/kaitai_struct/issues/94)
- [ ] [C# ReadBytes size expression type mismatch](https://github.com/kaitai-io/kaitai_struct/issues/93)
- [ ] [out of range enums](https://github.com/kaitai-io/kaitai_struct/issues/92)
- [ ] [Fix-length zero-padded string handling](https://github.com/kaitai-io/kaitai_struct/issues/91)
- [ ] [prohibit / workaround reserved words](https://github.com/kaitai-io/kaitai_struct/issues/90)
- [ ] [invalid parent type](https://github.com/kaitai-io/kaitai_struct/issues/89)
- [ ] [prohibit sub-type and field name collision](https://github.com/kaitai-io/kaitai_struct/issues/86)
